#
#Thu Dec 26 07:43:56 AMT 2024
WhatsNewVersion=v6.2
AddressCreationCardShown=true
StoreDBPassphrase=false
InitialRandomDBPassphrase=false
PrivacyDeliveryReceiptsSet=true
CurrentTheme=SYSTEM
DesktopWindowState={\n    "width"\: 1728,\n    "height"\: 1080,\n    "x"\: 0,\n    "y"\: 37\n}
OneHandUICardShown=true
NewDatabaseInitialized=true
CurrentThemeIds={}
OneHandUI=false
LastMigratedVersionCode=261
ChatLastStart=1735182319278
ChatStopped=false
OnboardingStage=OnboardingComplete
