return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    opts = {
      highlight = { enable = true },
      ensure_installed = {
        "rust",
        "go",
        "gomod",
        "gowork",
        "gosum",
        "bash",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "vim",
        "yaml",
        "cpp",
        "elixir",
        "heex",
        "hurl",
      },
    },
  },
}
